[[edge_functions]]
path = "/get-country"
function = "location"

[[redirects]]
from = "/*"
to = "/"
status = 404

[[headers]]
	for = "/img/*"
	[headers.values]
		Cache-Control = "public, max-age=2592000, immutable"